services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/hummind-app:${IMAGE_TAG:-main}
    container_name: hummind-frontend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - hummind-network

networks:
  hummind-network:
    name: hummind-network
    driver: bridge
