"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { CourseDetail } from "../../../../../../../src/lib/course/courseDetail";
import type { LiveCourseStep, LiveQuizQuestion } from "../../../../../../../src/lib/course/liveCourse";
import { createMessageId } from "../_components/course-live-data";

type TutorAction =
  | "INTRO"
  | "ASK"
  | "PROGRESS"
  | "QUIZ_FEEDBACK"
  | "EXERCISE_FEEDBACK";

export type TutorSuggestion = {
  label: string;
  intent: "ask" | "next_step";
};

export type TutorMessage = {
  id: string;
  role: "assistant" | "user";
  content: string[];
  title?: string;
  suggestions?: TutorSuggestion[];
  evaluation?: TutorReply["evaluation"];
  kind?: "text" | "quiz_question";
  quizQuestion?: LiveQuizQuestion;
  quizCursor?: number;
  quizTotal?: number;
};

type TutorReply = {
  message: string;
  suggestedPrompts: TutorSuggestion[];
  evaluation: "none" | "correct" | "incorrect" | "partial" | "strong";
  canContinue: boolean;
};

type StepSession = {
  started: boolean;
  pending: boolean;
  pendingLabel: string | null;
  messages: TutorMessage[];
  activeQuizMessageId: string | null;
  quizCursor: number;
  quizAttempts: number;
  lastQuizChoiceIndex: number | null;
  lastQuizEvaluation: boolean | null;
  exerciseDraft: string;
  exerciseEvaluation: "none" | "partial" | "strong";
  exerciseCanContinue: boolean;
  error: string | null;
};

type UseCourseLiveTutorSessionArgs = {
  course: CourseDetail;
  step: LiveCourseStep;
  nextStep: LiveCourseStep | null;
  locale: string;
};

type UseCourseLiveTutorSessionResult = {
  messages: TutorMessage[];
  sessionMessagesByStepId: Record<string, TutorMessage[]>;
  pending: boolean;
  pendingLabel: string | null;
  error: string | null;
  activeQuizMessageId: string | null;
  quizCursor: number;
  activeQuizQuestion: LiveQuizQuestion | null;
  lastQuizChoiceIndex: number | null;
  lastQuizEvaluation: boolean | null;
  quizCompleted: boolean;
  exerciseDraft: string;
  exerciseEvaluation: "none" | "partial" | "strong";
  exerciseCanContinue: boolean;
  askTutor: (message: string) => Promise<void>;
  triggerSuggestedPrompt: (prompt: string) => Promise<void>;
  progressToNextStep: (
    prompt: string,
    onNavigate: () => void,
  ) => Promise<void>;
  answerQuiz: (choiceIndex: number, onStepComplete?: () => void) => Promise<void>;
  updateExerciseDraft: (value: string) => void;
  submitExerciseAnswer: () => Promise<void>;
};

function getDefaultSession(): StepSession {
  return {
    started: false,
    pending: false,
    pendingLabel: null,
    messages: [],
    activeQuizMessageId: null,
    quizCursor: 0,
    quizAttempts: 0,
    lastQuizChoiceIndex: null,
    lastQuizEvaluation: null,
    exerciseDraft: "",
    exerciseEvaluation: "none",
    exerciseCanContinue: false,
    error: null,
  };
}

function getPendingLabel(action: TutorAction, step: LiveCourseStep) {
  if (action === "QUIZ_FEEDBACK") {
    return "Le tuteur verifie ta reponse...";
  }

  if (action === "EXERCISE_FEEDBACK") {
    return "Le tuteur lit ta tentative...";
  }

  if (action === "PROGRESS") {
    return step.kind === "quiz"
      ? "Le tuteur prepare la suite du quiz..."
      : "Le tuteur prepare la suite du cours...";
  }

  if (action === "INTRO") {
    return step.kind === "exercise"
      ? "Le tuteur prepare une premiere piste..."
      : "Hummind AI reflechit...";
  }

  return "Hummind AI reflechit...";
}

function getQuizChoiceLabel(index: number) {
  return String.fromCharCode(65 + index);
}

function getLiveSessionStorageKey(courseId: string) {
  return `hummind-live:sessions:${courseId}`;
}

function readStoredSessions(courseId: string): Record<string, StepSession> {
  if (!courseId || typeof window === "undefined") {
    return {};
  }

  try {
    const rawValue = window.localStorage.getItem(
      getLiveSessionStorageKey(courseId),
    );

    if (!rawValue) {
      return {};
    }

    const parsed = JSON.parse(rawValue) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return {};
    }

    return parsed as Record<string, StepSession>;
  } catch {
    return {};
  }
}

// All suggestions are generated by the AI contextually — no hardcoded buttons.

/**
 * Walk through every session message and collect quiz/exercise evaluations
 * already produced by the AI (or recorded locally). The tutor reuses this
 * list as `learnerContext.previousQuizResults` so it remembers across turns
 * which notions the learner has succeeded or struggled on.
 */
function buildPreviousQuizResults(
  sessions: Record<string, StepSession>,
  maxResults = 12,
): string[] {
  const results: string[] = [];
  for (const session of Object.values(sessions)) {
    if (!session.messages?.length) continue;
    for (const msg of session.messages as Array<{ role?: string; evaluation?: string }>) {
      if (msg.role !== "assistant" || !msg.evaluation) continue;
      if (msg.evaluation === "none") continue;
      results.push(msg.evaluation);
    }
  }
  return results.slice(-maxResults);
}

/**
 * Build a summary of recent chat history for the AI to understand context.
 * Returns last N messages as a compact string so the tutor knows what was discussed.
 */
function buildChatHistorySummary(
  sessions: Record<string, StepSession>,
  maxMessages = 6,
): string[] {
  const allMessages: string[] = [];
  for (const session of Object.values(sessions)) {
    if (!session.messages?.length) continue;
    for (const msg of session.messages.slice(-4) as Array<{ role?: string; content?: string[] }>) {
      if (!msg.role || !msg.content?.length) continue;
      const prefix = msg.role === "assistant" ? "Tuteur" : "Apprenant";
      const text = msg.content[0];
      if (typeof text === "string" && text.trim()) {
        allMessages.push(`${prefix}: ${text.slice(0, 120)}`);
      }
    }
  }
  return allMessages.slice(-maxMessages);
}

function buildStepIntroMessage(step: LiveCourseStep) {
  if (step.kind === "quiz") {
    return "Parfait, passons a une verification rapide.";
  }

  if (step.kind === "exercise") {
    return "Tres bien, passons a la mise en pratique.";
  }

  return "";
}

function compactTutorMessage(value: string, maxLength = 170) {
  const normalized = value.replace(/\s+/g, " ").trim();
  if (!normalized) return "";

  const sentenceMatch = normalized.match(/^.*?[.!?](?:\s|$)/);
  const firstSentence = sentenceMatch ? sentenceMatch[0].trim() : normalized;
  if (firstSentence.length <= maxLength) return firstSentence;

  return `${firstSentence.slice(0, maxLength - 1).trimEnd()}…`;
}

/**
 * Minimal fallback used only when the AI API is unavailable.
 * No hardcoded suggestions — the chat input is always available.
 */
function buildFallbackReply(args: {
  action: TutorAction;
  step: LiveCourseStep;
  nextStep: LiveCourseStep | null;
  progressionEnabled: boolean;
  learnerMessage: string;
  evaluation?: boolean | "partial" | "strong" | null;
}): TutorReply {
  if (args.action === "QUIZ_FEEDBACK") {
    return {
      message: args.evaluation === true
        ? "Bien joue !"
        : "Pas tout a fait. Relis la notion et reessaie.",
      suggestedPrompts: [],
      evaluation: args.evaluation === true ? "correct" : "incorrect",
      canContinue: args.evaluation === true,
    };
  }

  if (args.action === "EXERCISE_FEEDBACK") {
    return {
      message: args.evaluation === "strong"
        ? "Bonne tentative, tu peux avancer."
        : "Continue, tu es sur la bonne voie.",
      suggestedPrompts: [],
      evaluation: typeof args.evaluation === "string" ? args.evaluation : "none",
      canContinue: args.evaluation === "strong",
    };
  }

  if (args.action === "PROGRESS") {
    return {
      message: "Parfait, on passe a la suite.",
      suggestedPrompts: [],
      evaluation: "none",
      canContinue: true,
    };
  }

  return {
    message: "Pose ta question dans le chat, je suis la pour t'aider.",
    suggestedPrompts: [],
    evaluation: "none",
    canContinue: false,
  };
}

async function requestTutorReply(args: {
  action: TutorAction;
  course: CourseDetail;
  step: LiveCourseStep;
  nextStep: LiveCourseStep | null;
  progressionEnabled: boolean;
  locale: string;
  quizCursor?: number;
  learnerMessage?: string;
  attemptCount?: number;
  cumulativeAttempts?: number;
  evaluation?: boolean | "partial" | "strong" | null;
  selectedChoiceIndex?: number | null;
  selectedChoiceText?: string;
  expectedAnswer?: string;
  learnerContext?: Record<string, unknown>;
}) {
  const fallback = buildFallbackReply({
    action: args.action,
    step: args.step,
    nextStep: args.nextStep,
    progressionEnabled: args.progressionEnabled,
    learnerMessage: args.learnerMessage || "",
    evaluation: args.evaluation ?? null,
  });

  try {
    const response = await fetch("/api/ai/live-tutor", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        action: args.action,
        language: args.locale,
        course: {
          id: args.course.id,
          title: args.course.title,
          description: args.course.description,
          objectives: args.course.objectives,
          level: args.course.level,
          domain: args.course.domain,
        },
        step: {
          id: args.step.id,
          moduleTitle: args.step.moduleTitle,
          title: args.step.title,
          kind: args.step.kind,
          sourceLines: args.step.sourceLines,
          contextLines: args.step.contextLines,
          exercisePrompt: args.step.exercisePrompt,
          exerciseSolution: args.step.exerciseSolution,
          quizQuestions: args.step.quizQuestions,
          quizCursor: typeof args.quizCursor === "number" ? args.quizCursor : 0,
        },
        nextStep: args.nextStep
          ? {
              id: args.nextStep.id,
              title: args.nextStep.title,
              kind: args.nextStep.kind,
            }
          : null,
        progressionEnabled: args.progressionEnabled,
        learner: {
          message: args.learnerMessage || "",
          attemptCount: args.attemptCount ?? 0,
          cumulativeAttempts: args.cumulativeAttempts ?? 0,
          evaluation:
            args.evaluation === true
              ? "correct"
              : args.evaluation === false
                ? "incorrect"
                : args.evaluation || "unknown",
          selectedChoiceIndex:
            typeof args.selectedChoiceIndex === "number"
              ? args.selectedChoiceIndex
              : null,
          selectedChoiceLabel:
            typeof args.selectedChoiceIndex === "number"
              ? getQuizChoiceLabel(args.selectedChoiceIndex)
              : "",
          selectedChoiceText: args.selectedChoiceText || "",
          expectedAnswer: args.expectedAnswer || "",
        },
        learnerContext: args.learnerContext ?? {},
      }),
    });

    if (!response.ok) {
      return fallback;
    }

    const payload = (await response.json()) as { reply?: TutorReply };
    const reply = payload.reply;
    if (!reply?.message) {
      return fallback;
    }

    // Optimisation #4: trust AI suggestions when available
    return reply;
  } catch {
    return fallback;
  }
}

export function useCourseLiveTutorSession({
  course,
  step,
  nextStep,
  locale,
}: UseCourseLiveTutorSessionArgs): UseCourseLiveTutorSessionResult {
  const [sessions, setSessions] = useState<Record<string, StepSession>>(() =>
    readStoredSessions(course.id),
  );
  const startingStepIdsRef = useRef<Record<string, boolean>>({});

  const session = sessions[step.id] ?? getDefaultSession();

  useEffect(() => {
    if (typeof window === "undefined" || !course.id) return;

    try {
      const storageKey = getLiveSessionStorageKey(course.id);

      if (Object.keys(sessions).length === 0) {
        window.localStorage.removeItem(storageKey);
        return;
      }

      window.localStorage.setItem(storageKey, JSON.stringify(sessions));
    } catch {
      // Ignore storage failures and keep the live usable.
    }
  }, [course.id, sessions]);

  const activeQuizQuestion = useMemo(() => {
    if (step.kind !== "quiz") return null;
    return step.quizQuestions[session.quizCursor] ?? null;
  }, [session.quizCursor, step]);

  const quizCompleted =
    step.kind === "quiz" && session.quizCursor >= step.quizQuestions.length;
  const progressionEnabled = useMemo(() => {
    if (!nextStep) return false;
    if (step.kind === "lesson") return true;
    if (step.kind === "quiz") return quizCompleted;
    return session.exerciseCanContinue;
  }, [nextStep, quizCompleted, session.exerciseCanContinue, step.kind]);

  const updateSession = useCallback(
    (
      stepId: string,
      updater: (current: StepSession) => StepSession,
    ) => {
      setSessions((currentSessions) => {
        const current = currentSessions[stepId] ?? getDefaultSession();
        return {
          ...currentSessions,
          [stepId]: updater(current),
        };
      });
    },
    [],
  );

  const appendAssistantMessage = useCallback(
    (stepId: string, title: string | undefined, reply: TutorReply) => {
      updateSession(stepId, (current) => ({
        ...current,
        pending: false,
        pendingLabel: null,
        error: null,
        messages: [
          ...current.messages,
          {
            id: createMessageId("assistant"),
            role: "assistant",
            title,
            content: [reply.message],
            suggestions: reply.suggestedPrompts,
            evaluation: reply.evaluation,
            kind: "text",
          },
        ],
      }));
    },
    [updateSession],
  );

  const appendQuizQuestionMessage = useCallback(
    (
      stepId: string,
      question: LiveQuizQuestion,
      questionCursor: number,
      questionTotal: number,
      suggestions: TutorSuggestion[] = [],
    ) => {
      const messageId = createMessageId("assistant");

      updateSession(stepId, (current) => ({
        ...current,
        activeQuizMessageId: messageId,
        messages: [
          ...current.messages,
          {
            id: messageId,
            role: "assistant",
            title: "Verification rapide",
            content: [question.question],
            kind: "quiz_question",
            quizQuestion: question,
            quizCursor: questionCursor,
            quizTotal: questionTotal,
            suggestions,
          },
        ],
      }));
    },
    [updateSession],
  );

  const appendUserMessage = useCallback(
    (stepId: string, text: string) => {
      updateSession(stepId, (current) => ({
        ...current,
        messages: [
          ...current.messages,
          {
            id: createMessageId("user"),
            role: "user",
            content: [text],
          },
        ],
      }));
    },
    [updateSession],
  );

  useEffect(() => {
    if (
      session.started ||
      session.pending ||
      startingStepIdsRef.current[step.id]
    ) {
      return;
    }

    startingStepIdsRef.current[step.id] = true;

    if (step.kind === "quiz") {
      const initialQuizQuestionId = step.quizQuestions[0]
        ? createMessageId("assistant")
        : null;

      queueMicrotask(() => {
        updateSession(step.id, (current) => ({
          ...current,
          started: true,
          pending: false,
          pendingLabel: null,
          error: null,
          messages:
            current.messages.length > 0
              ? current.messages
              : [
                  {
                    id: createMessageId("assistant"),
                    role: "assistant",
                    title: "Hummind AI",
                    content: [buildStepIntroMessage(step)],
                    suggestions: [],
                    kind: "text",
                  },
                  ...(step.quizQuestions[0]
                    ? [
                        {
                          id: initialQuizQuestionId as string,
                          role: "assistant" as const,
                          title: "Verification rapide",
                          content: [step.quizQuestions[0].question],
                          kind: "quiz_question" as const,
                          quizQuestion: step.quizQuestions[0],
                          quizCursor: 0,
                          quizTotal: step.quizQuestions.length,
                        },
                      ]
                    : []),
                ],
          activeQuizMessageId:
            current.messages.length > 0
              ? current.activeQuizMessageId
              : initialQuizQuestionId,
        }));

        delete startingStepIdsRef.current[step.id];
      });

      return;
    }

    queueMicrotask(() => {
      updateSession(step.id, (current) => ({
        ...current,
        pending: true,
        pendingLabel: getPendingLabel("INTRO", step),
        error: null,
      }));

      void requestTutorReply({
        action: "INTRO",
        course,
        step,
        nextStep,
        progressionEnabled: step.kind === "lesson" && Boolean(nextStep),
        locale,
        quizCursor: 0,
        learnerContext: {
          chatHistory: buildChatHistorySummary(sessions),
          previousQuizResults: buildPreviousQuizResults(sessions),
        },
      })
        .then((reply) => {
          updateSession(step.id, (current) => ({
            ...current,
            started: true,
            pending: false,
            pendingLabel: null,
            error: null,
            messages:
              current.messages.length > 0
                ? current.messages
                : [
                    {
                      id: createMessageId("assistant"),
                      role: "assistant",
                      title: "Hummind AI",
                      content: [reply.message],
                      suggestions: reply.suggestedPrompts,
                      kind: "text",
                    },
                  ],
            activeQuizMessageId: current.activeQuizMessageId,
          }));
        })
        .finally(() => {
          delete startingStepIdsRef.current[step.id];
        });
    });
  }, [
    course,
    locale,
    nextStep,
    session.pending,
    session.started,
    sessions,
    step,
    updateSession,
  ]);

  const askTutor = useCallback(
    async (message: string) => {
      const trimmedMessage = message.trim();
      if (!trimmedMessage) return;

      appendUserMessage(step.id, trimmedMessage);
      updateSession(step.id, (current) => ({
        ...current,
        pending: true,
        pendingLabel: getPendingLabel("ASK", step),
        error: null,
      }));

      const reply = await requestTutorReply({
        action: "ASK",
        course,
        step,
        nextStep,
        progressionEnabled,
        locale,
        quizCursor: session.quizCursor,
        learnerMessage: trimmedMessage,
        attemptCount: session.quizAttempts,
        learnerContext: {
          chatHistory: buildChatHistorySummary(sessions),
          previousQuizResults: buildPreviousQuizResults(sessions),
        },
      });

      if (step.kind === "quiz") {
        const activeQuestion = step.quizQuestions[session.quizCursor];

        appendAssistantMessage(step.id, "Hummind AI", {
          ...reply,
          message: compactTutorMessage(reply.message, 150) || reply.message,
        });

        updateSession(step.id, (current) => ({
          ...current,
          activeQuizMessageId: null,
          lastQuizChoiceIndex: null,
          lastQuizEvaluation: null,
        }));

        if (activeQuestion) {
          await new Promise((resolve) => {
            setTimeout(resolve, 180);
          });

          appendQuizQuestionMessage(
            step.id,
            activeQuestion,
            session.quizCursor,
            step.quizQuestions.length,
            reply.suggestedPrompts,
          );
        }

        return;
      }

      // For all step kinds: use AI-generated suggestions directly
      appendAssistantMessage(step.id, "Hummind AI", reply);
    },
    [
      appendAssistantMessage,
      appendQuizQuestionMessage,
      appendUserMessage,
      course,
      locale,
      nextStep,
      progressionEnabled,
      session.quizAttempts,
      session.quizCursor,
      sessions,
      step,
      updateSession,
    ],
  );

  const triggerSuggestedPrompt = useCallback(
    async (prompt: string) => {
      await askTutor(prompt);
    },
    [askTutor],
  );

  const progressToNextStep = useCallback(
    async (prompt: string, onNavigate: () => void) => {
      if (!nextStep) return;

      const trimmedPrompt = prompt.trim();
      if (!trimmedPrompt) return;

      appendUserMessage(step.id, trimmedPrompt);
      updateSession(step.id, (current) => ({
        ...current,
        pending: true,
        pendingLabel: getPendingLabel("PROGRESS", step),
        error: null,
      }));

      // Call the AI for a narrative transition message
      const reply = await requestTutorReply({
        action: "PROGRESS",
        course,
        step,
        nextStep,
        progressionEnabled: true,
        locale,
        quizCursor: session.quizCursor,
        learnerContext: {
          chatHistory: buildChatHistorySummary(sessions),
          previousQuizResults: buildPreviousQuizResults(sessions),
        },
      });

      appendAssistantMessage(step.id, "Hummind AI", {
        ...reply,
        suggestedPrompts: [],
      });

      // Mark current step as completed before navigating
      updateSession(step.id, (current) => ({
        ...current,
        pending: false,
        pendingLabel: null,
        started: true,
      }));

      // Navigate after a brief pause so the learner sees the transition message
      await new Promise((resolve) => {
        setTimeout(resolve, 800);
      });
      onNavigate();
    },
    [
      appendAssistantMessage,
      appendUserMessage,
      course,
      locale,
      nextStep,
      session.quizCursor,
      sessions,
      step,
      updateSession,
    ],
  );

  const answerQuiz = useCallback(
    async (choiceIndex: number, onStepComplete?: () => void) => {
      if (step.kind !== "quiz") return;

      const question = step.quizQuestions[session.quizCursor];
      if (!question) return;

      const isCorrect = question.correctIndexes.includes(choiceIndex);
      const isLastQuestion = session.quizCursor >= step.quizQuestions.length - 1;
      const nextAttemptCount = isCorrect ? 0 : session.quizAttempts + 1;
      const choiceText = question.choices[choiceIndex] || "";
      let quizGuidanceSuggestions: TutorSuggestion[] = [];

      appendUserMessage(
        step.id,
        `Je choisis ${getQuizChoiceLabel(choiceIndex)}. ${choiceText}`,
      );

      updateSession(step.id, (current) => ({
        ...current,
        pending: true,
        pendingLabel: getPendingLabel("QUIZ_FEEDBACK", step),
        lastQuizChoiceIndex: choiceIndex,
        lastQuizEvaluation: isCorrect,
        quizAttempts: nextAttemptCount,
        error: null,
      }));

      if (isCorrect) {
        appendAssistantMessage(step.id, "Hummind AI", {
          message: "Correct.",
          suggestedPrompts: [],
          evaluation: "correct",
          canContinue: true,
        });
      } else {
        const reply = await requestTutorReply({
          action: "QUIZ_FEEDBACK",
          course,
          step,
          nextStep,
          progressionEnabled: false,
          locale,
          quizCursor: session.quizCursor,
          learnerMessage: choiceText,
          attemptCount: nextAttemptCount,
          evaluation: false,
          selectedChoiceIndex: choiceIndex,
          selectedChoiceText: choiceText,
          learnerContext: {
            chatHistory: buildChatHistorySummary(sessions),
            previousQuizResults: buildPreviousQuizResults(sessions),
          },
        });

        appendAssistantMessage(step.id, "Hummind AI", {
          ...reply,
          message: compactTutorMessage(reply.message, 150) || reply.message,
          suggestedPrompts: [],
        });

        quizGuidanceSuggestions = reply.suggestedPrompts;
      }

      const nextQuizCursor = Math.min(session.quizCursor + 1, step.quizQuestions.length);
      const nextQuizQuestion = step.quizQuestions[nextQuizCursor] ?? null;

      updateSession(step.id, (current) => {
        if (!isCorrect) {
          return {
            ...current,
            pending: false,
            pendingLabel: null,
            activeQuizMessageId: null,
            lastQuizChoiceIndex: null,
            lastQuizEvaluation: null,
          };
        }

        return {
          ...current,
          pending: false,
          pendingLabel: null,
          activeQuizMessageId: null,
          quizCursor: Math.min(current.quizCursor + 1, step.quizQuestions.length),
          quizAttempts: 0,
          lastQuizChoiceIndex: null,
          lastQuizEvaluation: null,
        };
      });

      if (isCorrect && nextQuizQuestion) {
        await new Promise((resolve) => {
          setTimeout(resolve, 320);
        });

        appendQuizQuestionMessage(
          step.id,
          nextQuizQuestion,
          nextQuizCursor,
          step.quizQuestions.length,
        );
      }

      if (!isCorrect) {
        await new Promise((resolve) => {
          setTimeout(resolve, 180);
        });

        appendQuizQuestionMessage(
          step.id,
          question,
          session.quizCursor,
          step.quizQuestions.length,
          quizGuidanceSuggestions,
        );
      }

      if (isCorrect && isLastQuestion && nextStep && onStepComplete) {
        await new Promise((resolve) => {
          setTimeout(resolve, 420);
        });

        onStepComplete();
      }
    },
    [
      appendAssistantMessage,
      appendQuizQuestionMessage,
      appendUserMessage,
      course,
      locale,
      nextStep,
      session.quizAttempts,
      session.quizCursor,
      sessions,
      step,
      updateSession,
    ],
  );

  const updateExerciseDraft = useCallback(
    (value: string) => {
      updateSession(step.id, (current) => ({
        ...current,
        exerciseDraft: value,
      }));
    },
    [step.id, updateSession],
  );

  const submitExerciseAnswer = useCallback(async () => {
    if (step.kind !== "exercise") return;
    const answer = session.exerciseDraft.trim();
    if (!answer) return;

    appendUserMessage(step.id, answer);
    updateSession(step.id, (current) => ({
      ...current,
      pending: true,
      pendingLabel: getPendingLabel("EXERCISE_FEEDBACK", step),
      error: null,
    }));

    const reply = await requestTutorReply({
      action: "EXERCISE_FEEDBACK",
      course,
      step,
      nextStep,
      progressionEnabled: Boolean(nextStep),
      locale,
      quizCursor: session.quizCursor,
      learnerMessage: answer,
      evaluation: "partial",
      expectedAnswer: step.exerciseSolution,
      learnerContext: {
        chatHistory: buildChatHistorySummary(sessions),
        previousQuizResults: buildPreviousQuizResults(sessions),
      },
    });

    appendAssistantMessage(step.id, "Hummind AI", reply);

    updateSession(step.id, (current) => ({
      ...current,
      pending: false,
      pendingLabel: null,
      exerciseEvaluation:
        reply.evaluation === "strong" ? "strong" : "partial",
      exerciseCanContinue: reply.canContinue,
    }));
  }, [
    appendAssistantMessage,
    appendUserMessage,
    course,
    locale,
    nextStep,
    session.exerciseDraft,
    session.quizCursor,
    sessions,
    step,
    updateSession,
  ]);

  return {
    messages: session.messages,
    sessionMessagesByStepId: Object.fromEntries(
      Object.entries(sessions).map(([stepId, stepSession]) => [
        stepId,
        stepSession.messages,
      ]),
    ),
    pending: session.pending,
    pendingLabel: session.pendingLabel,
    error: session.error,
    activeQuizMessageId: session.activeQuizMessageId,
    quizCursor: session.quizCursor,
    activeQuizQuestion,
    lastQuizChoiceIndex: session.lastQuizChoiceIndex,
    lastQuizEvaluation: session.lastQuizEvaluation,
    quizCompleted,
    exerciseDraft: session.exerciseDraft,
    exerciseEvaluation: session.exerciseEvaluation,
    exerciseCanContinue: session.exerciseCanContinue,
    askTutor,
    triggerSuggestedPrompt,
    progressToNextStep,
    answerQuiz,
    updateExerciseDraft,
    submitExerciseAnswer,
  };
}
