services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/hummind-backend:${IMAGE_TAG:-main}
    container_name: hummind-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5500:5500"
    networks:
      - hummind-network

networks:
  hummind-network:
    name: hummind-network
    driver: bridge
